### ISSUE TITLE
Initial docs page shows <svg> code for headings

### ISSUE THREAD

**Issue by c23gooey** [gregberge/smooth-doc#14]
## 🐛 Bug Report

After following the get started step, when I browse to the initial documentation page, there are <svg> code blocks in the headings (see screenshot)

## To Reproduce

Follow get started install.
Click Browse Docs button
Observe <svg> code blocks (see screenshot)

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages smooth-doc,gatsby,react,react-dom --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
 - Memory: 73.74 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.0 - /usr/local/bin/node
 - npm: 6.14.4 - /usr/local/bin/npm
## npmPackages:
 - gatsby: ^2.15.18 => 2.24.77
 - react: ^16.10.1 => 16.14.0
 - react-dom: ^16.10.1 => 16.14.0
 - smooth-doc: ^5.0.4 => 5.1.1
```
![Screen Shot 2020-10-15 at 4 34 49 pm](https://user-images.githubusercontent.com/478128/96081363-dc957400-0f04-11eb-8fda-86aef112e42a.png)

**Comment by qbereau** [comment]
can confirm, i'm getting the same thing

**Comment by gregberge** [comment]
Hello, I just tried to create a new project and I don't experience that, what is your browser? Do you have something specific?

Could you try to find what is the cause of the issue? The problem is probably located in this package: https://github.com/gregberge/smooth-doc/tree/master/smooth-doc/src/plugins/gatsby-remark-autolink-headers

**Comment by qbereau** [comment]
it's happening on all my browsers Brave, Safari and FF.
It seems to be related to the svg being parsed/injected as a string instead of a raw element. 
See screenshot before and after removing the`""`

![Screenshot 2020-10-15 at 14 00 06](https://user-images.githubusercontent.com/417379/96120622-19567080-0eef-11eb-89b2-aaf08c377563.png)

![Screenshot 2020-10-15 at 14 00 45](https://user-images.githubusercontent.com/417379/96120637-1f4c5180-0eef-11eb-9fe6-8fb8c1163fef.png)

**Comment by dbismut** [comment]
I had the same issue. Deleting the `node_modules` and `.cache` folder and running `yarn` fixed it for me.

**Comment by gregberge** [comment]
OK, seems fixed!
